DROP TABLE IF EXISTS ALUMNO_PAGOS_BITACORA;
DROP TABLE IF EXISTS ALUMNO_PAGOS;
DROP TABLE IF EXISTS ALUMNO_CURSO;
DROP TABLE IF EXISTS CURSO_COSTOS;
DROP TABLE IF EXISTS ALUMNOS;
DROP TABLE IF EXISTS COSTOS;
DROP TABLE IF EXISTS CURSOS;
DROP TABLE IF EXISTS USUARIOS;

CREATE TABLE COSTOS
  (
    COSTO_ID       INTEGER PRIMARY KEY AUTO_INCREMENT,
    COSTO_ACTIVO   BOOLEAN,
    COSTO_MONTO    DECIMAL(19,2),
    COSTO_NOMBRE   VARCHAR(255),
    FECHA_CREACION DATE
  )DEFAULT CHARSET=UTF8;
  
CREATE TABLE CURSOS
  (
    CURSO_ID           INTEGER NOT NULL AUTO_INCREMENT,
    CURSO_FECHA_FIN    DATE,
    CURSO_FECHA_INICIO DATE,
    CURSO_NOMBRE       VARCHAR(255),
    CURSO_ESTATUS      INTEGER,
    FECHA_CREACION     DATE,
    PRIMARY KEY (CURSO_ID)
  )DEFAULT CHARSET=UTF8;
  
CREATE TABLE ALUMNOS
  (
    ALUMNO_ID         INTEGER NOT NULL AUTO_INCREMENT,
    ALUMNO_ACTIVO     BOOLEAN,
    ALUMNO_AP_MATERNO VARCHAR(255),
    ALUMNO_AP_PATERNO VARCHAR(255),
    ALUMNO_ESTATUS    INTEGER,
    ALUMNO_FECHA_NAC  DATE,
    ALUMNO_IMAGEN LONGBLOB,
    ALUMNO_NOMBRE    VARCHAR(255),
    ALUMNO_SALDO     DECIMAL(19,2),
    ALUMNO_TUTOR     VARCHAR(255),
    ALUMNO_EMAIL     VARCHAR(255),
    ALUMNO_TELEFONO1 VARCHAR(255),
    ALUMNO_TELEFONO2 VARCHAR(255),
    FECHA_CREACION   DATE,
    PRIMARY KEY (ALUMNO_ID)
  )DEFAULT CHARSET=UTF8;

CREATE TABLE USUARIOS
  (
    USUARIO_EMAIL    VARCHAR(255) NOT NULL,
    USUARIO_LOGIN    VARCHAR(255) NOT NULL,
    USUARIO_NOMBRE   VARCHAR(255) NOT NULL,
    USUARIO_PASSWORD VARCHAR(255) NOT NULL,
    USUARIO_ROL      INTEGER NOT NULL,
    PRIMARY KEY (USUARIO_LOGIN)
  )DEFAULT CHARSET=UTF8;
  
CREATE TABLE CURSO_COSTOS
  (
    CURSOCOSTO_ID            INTEGER NOT NULL AUTO_INCREMENT,
    COSTO_ID                 INTEGER NOT NULL,
    CURSOCOSTO_ACTIVO        BOOLEAN,
    CURSOCOSTO_APLICA_BECA   BOOLEAN,
    CURSOCOSTO_DIA_PAGO      INTEGER,
    CURSOCOSTO_GENERA_ADEUDO BOOLEAN,
    CURSOCOSTO_PAGO          BOOLEAN,
    CURSO_ID                 INTEGER NOT NULL,
    FECHA_CREACION           DATE,
    PRIMARY KEY (CURSOCOSTO_ID)
  )DEFAULT CHARSET=UTF8;
ALTER TABLE CURSO_COSTOS ADD FOREIGN KEY FK_CURSOCOSTOS_COSTO(COSTO_ID) REFERENCES COSTOS(COSTO_ID);
ALTER TABLE CURSO_COSTOS ADD FOREIGN KEY FK_CURSOCOSTOS_CURSO(CURSO_ID) REFERENCES CURSOS(CURSO_ID);
  
CREATE TABLE ALUMNO_CURSO
  (
    ALUMNOCURSO_ID        INTEGER NOT NULL AUTO_INCREMENT,
    ALUMNOCURSO_ACTIVO    BOOLEAN,
    ALUMNOCURSO_BECA      DECIMAL(19,2),
    ALUMNOCURSO_DESCUENTO DECIMAL(19,2),
    ALUMNOCURSO_INGRESO   DATE,
    ALUMNO_ID             INTEGER,
    CURSO_ID              INTEGER,
    PRIMARY KEY (ALUMNOCURSO_ID)
  )DEFAULT CHARSET=UTF8;
ALTER TABLE ALUMNO_CURSO ADD FOREIGN KEY FK_ALUMNOCURSO_ALUMNO(ALUMNO_ID) REFERENCES ALUMNOS(ALUMNO_ID);
ALTER TABLE ALUMNO_CURSO ADD FOREIGN KEY FK_ALUMNOCURSO_CURSO(CURSO_ID) REFERENCES CURSOS(CURSO_ID);
 
CREATE TABLE ALUMNO_PAGOS
  (
    ALUMNOPAGO_ID           INTEGER NOT NULL AUTO_INCREMENT,
    ALUMNOCURSO_ID          INTEGER,
    ALUMNOPAGO_ESTATUS      INTEGER,
    ALUMNOPAGO_FECHA_LIMITE TIMESTAMP,
    ALUMNOPAGO_FECHAPAGO    TIMESTAMP,
    ALUMNOPAGO_MONTO        DECIMAL(19,2),
    ALUMNOPAGO_PAGO         DECIMAL(19,2),
    CURSOCOSTO_ID           INTEGER,
    PRIMARY KEY (ALUMNOPAGO_ID)
  )DEFAULT CHARSET=UTF8;
ALTER TABLE ALUMNO_PAGOS ADD FOREIGN KEY FK_ALUMNOPAGOS_ALUMNOCURSO(ALUMNOCURSO_ID) REFERENCES ALUMNO_CURSO(ALUMNOCURSO_ID);
ALTER TABLE ALUMNO_PAGOS ADD FOREIGN KEY FK_ALUMNOPAGOS_CURSOCOSTO(CURSOCOSTO_ID) REFERENCES CURSO_COSTOS(CURSOCOSTO_ID);

CREATE TABLE ALUMNO_PAGOS_BITACORA
  (
    ALUMNOPAGOSBITACORA_ID         INTEGER NOT NULL AUTO_INCREMENT,
    ALUMNOPAGOSBITACORA_FECHA_PAGO TIMESTAMP,
    ALUMNOPAGOSBITACORA_PAGO       DECIMAL(19,2),
    ALUMNOPAGOSBITACORA_SALDO      DECIMAL(19,2),
    ALUMNOPAGO_ID                  INTEGER,
    PRIMARY KEY (ALUMNOPAGOSBITACORA_ID)
  )DEFAULT CHARSET=UTF8;
ALTER TABLE ALUMNO_PAGOS_BITACORA ADD FOREIGN KEY FK_ALUMNOPAGOBITACORA_ALUMNOPAGO(ALUMNOPAGO_ID) REFERENCES ALUMNO_PAGOS(ALUMNOPAGO_ID);

INSERT INTO USUARIOS (USUARIO_EMAIL,USUARIO_LOGIN,USUARIO_NOMBRE,USUARIO_PASSWORD,USUARIO_ROL) VALUES ('admin@admin.COM','admin','admin','$2a$10$k04LS6pxe6usCrZQcbm9weRPyIdzgNF0dVcN4iSJeLApFmET/5xzi',1);
INSERT INTO USUARIOS (USUARIO_EMAIL,USUARIO_LOGIN,USUARIO_NOMBRE,USUARIO_PASSWORD,USUARIO_ROL) VALUES ('user@user.COM','user','user','$2a$10$f8zD4gOVpxvmdRFTKJ3EH.E8lweCiHXOvSA8cxN.A5tyt819frE5q',2);
/*
$2a$10$k04LS6pxe6usCrZQcbm9weRPyIdzgNF0dVcN4iSJeLApFmET/5xzi	
$2a$10$f8zD4gOVpxvmdRFTKJ3EH.E8lweCiHXOvSA8cxN.A5tyt819frE5q	
*/
COMMIT;